[package]
name = "alpha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beta-na-me = { path = "../beta-na_me/",  optional = true }

[features]
debug = ["beta-na-me/debug"]
